### PR TITLE
Use built-in Fetch API from Node.js

### PR DESCRIPTION
**Pull request by jonkoops**

### CODE REVIEW

**Comment by Xiphe** [comment]
worth mentioning that this is only about tests and dev dependencies. The library never had node-fetch as a dependency and required passing a fetch implementation upon usage.

LGTM :hamster:

**Review by Xiphe — APPROVED** [review]

**Comment by Xiphe** [comment]
Tried to debug why ts-jest refuses to use build in fetch from node and gave up for now.

**Comment by jonkoops** [comment]
@Xiphe I have managed to get this working, and was able to remove both `node-fetch` and `cross-blob`. However, I am seeing some test failures that are seemingly unrelated.

It looks like OpenAPI Mocker returns invalid responses for some of the POST calls. It seems like it's not returning the updated responses.

Any idea what might be causing this?

**Comment by Xiphe** [comment]
What I found out: When you run these tests in isolation on `master` they fail in the same way. 

I don't have any more time to dig deeper but this indicates race condition to me :)

**Comment by jonkoops** [comment]
Yeah, I would concur. Very peculiar. Perhaps this is a bug in OpenAPI mocker?

**Comment by Xiphe** [comment]
Seems as if the same error happens also at random: https://github.com/cellular/oazapfts/pull/311 https://github.com/cellular/oazapfts/actions/runs/3310145388/jobs/5464028024

**Comment by Xiphe** [comment]
seems as if the current state on `master` is flaky

**Comment by jonkoops** [comment]
Ah, that's not good. I'll see if I can take a look at that. Perhaps we just skip verifying the exact contents of the response and just check that the response is actually ok?

**Comment by Xiphe** [comment]
might be a sensible solution. I'll also try to have a look and debug this week

**Comment by jonkoops** [comment]
Updated the tests so the `status` field is no longer present. We still might want to see if we can find a fix, but for now this allows the tests to pass.

**Pull request merged**
