### PR TITLE
Add support for properties outside allOf

### PR DESCRIPTION
**Pull request by piotr121993**

### CODE REVIEW

**Comment by piotr121993** [comment]
Resolves #61

**Comment by mrnickel** [comment]
We're experiencing and issue with this item as well. Merging this would be greatly appreciated

**Comment by Morriz** [comment]
Its been half a year. Can anybody approve or fix this PR?

**Review by shocklateboy92 — CHANGES_REQUESTED** [review]
Hey @piotr121993, thanks for this PR!
If you're still around, could you please rebase this on latest master and add a test for the new behavior?

**Comment by piotr121993** [comment]
Hi @shocklateboy92, I did the rebase and added a test as you asked.

**Review by shocklateboy92 — APPROVED** [review]
Woah, that was fast! Thanks. 

LGTM. I'm going to wait a few days to see if @fgnass or @jonkoops have any objections, then I'll merge it.

**Pull request merged**
