### PR TITLE
Convert generateApi to class, upgrade to TS 4.1.2, add exports

### PR DESCRIPTION
**Pull request by phryneas**
So, as already announced in https://github.com/cellular/oazapfts/issues/41#issuecomment-739527701, this PR would 
* convert the `generateApi` function to a class & expose it's inner functions, 
* add exports for a lot of functions 
* upgrade TS to version 4.1.2, using the new `factory` (`ts.create...` is deprecated now)

AST element properties are now marked as `readonly` and in some places they were deliberately modified. Since it didn't seem to cause any problems, I now just re-assign them with `Object.assign`, but that might break in a future TS version.

### CODE REVIEW

**Comment by kahirokunn** [comment]
@benjidea How about this one?

**Comment by fgnass** [comment]
@phryneas I'm so sorry, I was busy with other stuff and totally forgot about this PR! That being said, would you be interested in becoming an oazapfts maintainer?

**Comment by phryneas** [comment]
It is a tempting offer and thank you for the trust - but I already have too much on my plate with the whole Redux Toolkit + surrounding ecosystem, so unfortunately I won't have the time for that :slightly_smiling_face: 

Need me to fi up the conflicts on this one?

**Comment by fgnass** [comment]
That would be awesome if you could take a look at the conflicts, I started merging them but gave up on the halfway through.

**Comment by phryneas** [comment]
Okay, I've re-applied all changes to `generate.ts` manually and then merged the rest, I think this should be fine. Tests still work.

**Pull request merged**
